### ISSUE TITLE
Suggestion to hide the CSharpGraph component

### ISSUE THREAD

**Issue by DiellzaElshani** [BHoM/RDF_Prototypes#16]
#### Description:

I think the C# graph component confuses the users. We can include its functions within the toTTLGraph component. 
In grasshopper instead of: 
![image](https://user-images.githubusercontent.com/50298535/166797285-a9b31b42-8caa-4557-ae5d-77d993b6c15b.png)

it would look like this: 
![image](https://user-images.githubusercontent.com/50298535/166795822-09af7f94-b114-4450-96cc-fa3472792546.png)

**Comment by alelom** [comment]
The method like this is already existing. It's called `BH.Engine.RDF.Compute.TTLGraph()`, it takes an `IObject`, internally computes a `CSharpGraph` and then returns a TTL string:

https://github.com/BHoM/RDF_Prototypes/blob/cdd6cee76e9fb286bb4d55972ca4a95a66cffa1e/RDF_Engine/Compute/TTLGraph.cs#L21-L28
