### ISSUE TITLE
Support for nested custom objects

### ISSUE THREAD

**Issue by DiellzaElshani** [BHoM/RDF_Prototypes#24]
#### Description:

Currently toTTLGraph doesn't support the conversion of a CustomObject which takes as input property another CustomObject. 
For example, for the following object:
![image](https://user-images.githubusercontent.com/50298535/171034812-a62aebd0-c4aa-495b-8b89-8122f195bf47.png)

The TTL graph does not create a class named segment. (It only creates an owl class for the last CustomObject, see image). 
![customObvject](https://user-images.githubusercontent.com/50298535/171034905-75cc0225-4f27-4772-8f0f-c39df6583617.png)

(I will add triples to exemplify how it should look like)

**Comment by alelom** [comment]
@DiellzaElshani as soon as you add examples I will work on this.
