### ISSUE TITLE
owl:DatatypeProperty is missing in the current converter

### ISSUE THREAD

**Issue by DiellzaElshani** [BHoM/RDF_Prototypes#28]
#### Description:

![image](https://user-images.githubusercontent.com/50298535/174350751-b734fb59-3a60-461e-8daa-b6c64538f01b.png)

#### Expected behaviour:

Instead they should be owl:DatatypeProperty

**Comment by danielhz** [comment]
To my knowledge, `:BG.oM.Geometry.Polyline.ControlPoints` is an `owl:ObjectProperty` because its range is `rdf:List`, which is not a literal. Otherwise, if this property range were a literal datatype, then it would be of the type `owl:DatatypeProperty`.
