### ISSUE TITLE
Point.X has to be of type owl:DatatypeProperty,

### ISSUE THREAD

**Issue by DiellzaElshani** [BHoM/RDF_Prototypes#33]
#### Description:

Point.X has to be of type owl:DatatypeProperty,

Comments from Daniel.

**Comment by alelom** [comment]
Yeah ok - however for the future you need to provide a Test file and/or example case where this happens. It can be difficult to tell where this is coming from.

**Comment by alelom** [comment]
I am closing this as there is no test file that replicates this issue and it is impossible to tell from where this observation comes from. In the latest version of the code, Point.X comes as DataType property.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/6352844/176130516-d67450bf-2dd2-4265-a32d-71792e199b2f.png">
