### ISSUE TITLE
Do geometries need to have another way of assigning IDs/URIs? Currently two identical points are recognized as the same one

### ISSUE THREAD

**Issue by DiellzaElshani** [BHoM/RDF_Prototypes#40]
Currently geometries use the HashCode to get an URI in the TLL format. However, when two identical points are input to the graph, they are not recognized as two points, but as one.  I understand that BHoM does not assign GUID to geometries, to handle complex geometries more efficiently. But this might bring some problems in the RDF graph representation. 

![image](https://user-images.githubusercontent.com/50298535/177342791-23c6691a-e671-4ade-a1f2-c3c32e3f2797.png)

#### Steps to reproduce:

I am not sure if that is a problem, maybe not. However, if yes:
I suggest having another way to generate the URI (rather than the hashcode). An way to approach this can be to: whenever we use geometry as input, always use a custom object where we also add a label (user input ID, or something similar); from where we generate a static, unique GUID (or we use the Custom Objects ID to refer to the geometry). 

![image](https://user-images.githubusercontent.com/50298535/177343478-623142f7-8531-4108-a447-47c0259af247.png)

**Comment by alelom** [comment]
Please see my reply https://github.com/BHoM/RDF_Prototypes/issues/41#issuecomment-1176311237.
