### ISSUE TITLE
RDF_Engine: Object/Data Properties domain should be the base type they originate from

### ISSUE THREAD

**Issue by DiellzaElshani** [BHoM/RDF_Prototypes#49]
#### Description:

Our current converter assigns properties to objects we see in Rhino. However, following BHoM conventions most of the properties that objects have are coming from interfaces they implement. 

Since, when converted to graph, interfaces are also classes, so properties should be assign to the parent class (BHoM interface). Eg, in the case of a room, the Perimeter's domain (ICurve Property's domain) should be IRegion, instead of Room.

![image](https://user-images.githubusercontent.com/50298535/195598840-cd138661-d5d0-4a1e-9bb0-225052626ac3.png)
![image](https://user-images.githubusercontent.com/50298535/195599645-e01f7701-72ab-4e76-b4cd-22dffed9cd4b.png)

#### Steps to reproduce:

The object properties derive from the interfaces they implement; these should be assigned to the interfaces instead of the object (Room class in this case).

**Comment by DiellzaElshani** [comment]
![image](https://user-images.githubusercontent.com/50298535/199517665-4c917ba0-8b8f-42c9-83f9-d17f311cedf1.png)

Our today's update, unfortunately, did not fix the problem. I tested, and all the properties are lost atm (including properties on the individuals' level).

**Comment by alelom** [comment]
Ok, I'll try to work on it today.

**Comment by alelom** [comment]
See #49 for connected effects to this issue.
