### ISSUE TITLE
Move GeometryAsClasses Property from TBOX to ABOX Class

### ISSUE THREAD

**Issue by polnischfrosch** [BHoM/RDF_Prototypes#70]
#### Description:
The Property that describes whether IGeometry should be considered as Classes or not, should be part of the ABOXsettings Class.

**Comment by alelom** [comment]
After chat with @DiellzaElshani and @polnischfrosch we agreed that this property does influence the individuals, but it does so by modifying the behavior of the T-box: by changing it you change what is a DataProperty vs an ObjectProperty, and by consequence when you change it you also change the individuals.
