### ISSUE TITLE
Create examples for 4 objects

### ISSUE THREAD

**Issue by alelom** [BHoM/RDF_Prototypes#8]
##### Actual data BHoM Objects - RDF
Review how the IRelations are made.

We only have HasProperty -> We need to have, for each property, a specific relation.

The range of a property: is it a Node or a Literal/Datatypes?

Ontology of 4 object - RDF

##### Next steps

Connecting with BOT - use BOT as RDF + alignment module bot element = oM
Make one RDF Jena Fuseki Server - Diellza

**Comment by DiellzaElshani** [comment]
The range of a property might be literal. Eg. If we want to set a name to a Column and Curve, which are both subclasses of BhomObject, We might do the following (I use bhom: as a prefix of our ontology): 

```
BHoM:Name rdf:type owl:datatypeProperty
BHoM:Name rdfs:domain bhom:BhomObject

bhom:Column rdfs :SubClassOf bhom:BhomObject
bhom:Curve rdfs:SubClassOf bhom:BhomObject

BHoM:Name rdfs:range xsd:string
```

**Comment by DiellzaElshani** [comment]
![image](https://user-images.githubusercontent.com/50298535/154854441-80e16703-6ad0-4ff5-bf81-37374ed05773.png)

Whereas the relation location can be modelled like this:  

```
bhom:location a owl:ObjectProperty
bhom:location rdfs:domain bhom:Column
bhom:location rdfs:range bhom:Curve 
```

**Comment by DiellzaElshani** [comment]
![image](https://user-images.githubusercontent.com/50298535/154854441-80e16703-6ad0-4ff5-bf81-37374ed05773.png)

Whereas the relation location can be modeled like this:  

```
bhom:location a owl:ObjectProperty
bhom:location rdfs:domain bhom:Column
bhom:location rdfs:range bhom:Curve 
```
