### ISSUE TITLE
Creating repositories via GraphDB adapter

### ISSUE THREAD

**Issue by DiellzaElshani** [BHoM/RDF_Prototypes#80]
#### Description:

What works currently:
- Opening GraphDB
- Deleting a repository in GraphDB
- Posting data to a repo that has already been defined in GraphDB

What we would like as features
- Create a repository,
- Post data to a specific/current active repository 

As much as I understood now, one should first create a Repo in GraphDB, only afterward we can post data to it. Is that correct @polnischfrosch ?

![image](https://user-images.githubusercontent.com/50298535/225873470-d566aa84-2987-42ad-95fd-01d1ea6a0586.png)

Here is the file I used: 
[Push to graphDB_error.zip](https://github.com/BHoM/RDF_Prototypes/files/11006404/Push.to.graphDB_error.zip)

I suggest we need to have also an update button in Grasshopper.

**Comment by polnischfrosch** [comment]
Was implemented in PR #87.
