### ISSUE TITLE
PullFromGraphDB component fails to load assembly through Grasshopper

### ISSUE THREAD

**Issue by polnischfrosch** [BHoM/RDF_Prototypes#93]
#### Description:
PullFromGraphDB component fails to load assembly. Only occurs when called from Grasshopper, test for PullFromGraphDB method is working fine.

Exception from Grasshopper component:
![image](https://user-images.githubusercontent.com/104036071/228969411-7a919511-2038-48e4-8a80-1484f2018cad.png)

Working method from test:
![image](https://user-images.githubusercontent.com/104036071/228972379-842fd91c-cde2-4400-8377-c507ab08494e.png)

### Test files:
[PullFromGraphDB.zip](https://github.com/BHoM/RDF_Prototypes/files/11116423/PullFromGraphDB.zip)

**Comment by alelom** [comment]
The reason for this is that the reference "HtmlAgilityPack" (screenshot 1) is not copied in the AppData/BHoM/Assemblies folder, so it cannot be found when the functionality is used via Grasshopper. We just need to add another PostBuild event that copies the HtmlAgilityPack dll in AppData. Just need to copy one of the existing events and replace the name of the dll with the correct one. The name of the HtmlAgilityPack dll can be found in the nuget package reference.
